module.exports = {
  purge: {
    content: [
      './app/**/*.php',
      './resources/**/*.php',
      './resources/views/partials/*.php',
      './resources/**/*.vue',
      './resources/**/*.js',
      '../../mu-plugins/acf-blocks/**/*.php',
      '../../mu-plugins/amp/templates/*.php',
    ],
    options: {
      safelist: [
        'tw-bg-brand-blue',
        'tw-bg-brand-blue-dark',
        'tw-bg-brand-blue-light',
        'tw-bg-brand-green',
        'tw-bg-brand-orange',
        'tw-bg-brand-orange-light',
        'tw-bg-brand-pink',
        'tw-bg-brand-red',
        'tw-bg-brand-yellow',
        'tw-bg-brand-turquesa',
        'tw-bg-gray-dark',
        'tw-bg-primary-light',
        'tw-bg-primary-dark',
        'tw-bg-secondary-light',
        'tw-bg-secondary-dark',
        'tw-text-brand-green',
        'tw-text-brand-blue-dark',
        'tw-text-brand-turquesa',
        'tw-text-brand-orange',
        'tw-text-brand-orange-dark',
        'tw-border-brand-orange',
        'tw-border-brand-green',
        'tw-border-brand-turquesa',
        'tw-border-brand-red',
        'tw-border-brand-blue-dark',
        'tw-text-8xl',
        'tw-fill-primary',
        'tw-fill-secondary',
        'tw-fill-green',
        'tw-fill-turquesa',
        'tw-fill-magenta',
        'tw-fill-primary-light',
        'tw-fill-secondary-light',
        'tw-fill-green-light',
        'tw-fill-turquesa-light',
        'tw-fill-magenta-light',
        'tw-mb-0',
      ],
    },
  },
  theme: {
    extend: {
      fill: theme => ({
        primary: theme('colors.primary'),
        secondary: theme('colors.secondary'),
        green: theme('colors.brand.green'),
        magenta: '#cd0e4d',
        turquesa: '#3cb497',
        'primary-light': theme('colors.primary-light'),
        'secondary-light': theme('colors.secondary-light'),
        'green-light': '#9dd056',
        'magenta-light': '#f01e63',
        'turquesa-light': '#5bc8ae',
      }),
      zIndex: {
        '60': 60,
      },
      boxShadow: {
        brand: '0 13px 50px 0 rgba(0, 0, 0, .4)',
        dot: '.5px .5px 2px 1px rgba(0, 0, 0, .4)',
        header: '0 3px 5px 0 hsla(300, 1%, 65%, .5)',
        button: '0px 4px 8px 0px rgba(0, 0, 0, 0.24)',
      },
      spacing: {
        '2/3': '66.666%',
        '3/2': '150%',
        square: '100%',
        '13': '3.25rem',
        '58px': '58px',
        '63px': '63px',
        '73px': '73.px',
        '40px': '40px',
        '28px': '28px',
        '64px': '64px',
        '48px': '48px',
        '16px': '16px',
        '24px': '24px',
        '12px': '12px',
        '37px': '37px',
        '32px': '32px',
        '15px': '15px',
        '52px': '52px',
      },
      minWidth: {
        '50': '50px',
        '75': '75px',
        '100': '100px',
        '200': '200px',
        '300': '300px',
        '600': '600px',
        '800': '800px',
        '96': '24rem',
      },
      minHeight: {
        '12': '3rem',
      },
      maxWidth: {
        '300': '300px',
        '400': '400px',
        '800': '800px',
        '1000': '1000px',
      },
      maxHeight: {
        '0': '0px',
      },
      height: {
        '72': '18rem',
        '96': '24rem',
        '128': '32rem',
        '152': '38rem',
        '176': '44rem',
        '44': '44px',
        '48px': '48px',
        '32px': '32px',
      },
      fontSize: {
        '2xl': '20px',
        '2xs': '.6rem',
        '8xl': '6rem',
        '12xl': '8rem',
        '24xl': '16rem',
        'xl': '18px',
        'base': '16px',
        '48px': '48px',
      },
      borderRadius: {
        xl: '0.625rem',
        '4px': '4px',
      },
      inset: {
        '1/5': '20%',
      },
      transitionProperty: {
        fade: ['visibility, opacity'],
      },
      width: {
        '44': '44px',
        '32px': '32px',
      },
      lineHeight: {
        '56px': '56px',
      },
    },
    colors: {
      brand: {
        orange: '#E35100',
        'orange-dark': '#C04400',
        'orange-light': '#F38D25',
        'orange-medium': '#F17F27',
        blue: '#005272',
        'blue-darker': '#012d3e',
        'blue-dark': '#3F83A3',
        'blue-light': '#4F99BB',
        yellow: '#E4B620',
        green: '#8DC055',
        pink: '#C94578',
        red: '#BB0034',
        turquesa: '#3cb497',
        'darkest': '#5A7C36',
        'green-blue': '#003F59',
        'feedback-orange': '#FAD2B3',
        'blue-darkest': '#004D6F',
        'green-darkest': '#5A7C36',
        'orange-darkest': '#943601',
        'pink-darkest': '#8A0026',
        'turquesa-darkest': '#2B7A6D',
      },
      gray: {
        lighter: '#F5F5F5',
        light: '#dadada',
        dark: '#666666',
        darker: '#222222',
        medium: '#767676',
        mid: '#939393',
        border: '#E2E1E0',
        pagination: '#eaeaea',
      },
      black: '#000000',
      primary: '#E35100',
      'primary-dark': '#C04400',
      'primary-light': '#F38D25',
      secondary: '#005272',
      'secondary-dark': '#3F83A3',
      'secondary-light': '#4F99BB',
      white: '#FFFFFF',
      hyperlinks: '#106AA3',
      'hyperlinks-visited': '#7F1F7D',
      transparent: 'transparent',
      'offwhite': '#FBFAF9',
      'cccccc': '#CCCCCC',
      'efedeb': '#efedeb',
      'C9C8C7': '#C9C8C7',
    },
    container: {
      center: true,
      padding: {
        DEFAULT: '1rem',
        sm: '2rem',
        md: '3rem',
        lg: '4rem',
        xl: '4rem',
        '2xl': '4rem',
        '3xl': '6rem',
        '24px': '24px',
      },
    },
    screens: {
      sm: '576px',
      md: '768px',
      lg: '1024px',
      xl: '1366px',
      '2xl': '1440px',
      '3xl': '1600px',
    },
    aspectRatio: {
      none: 0,
      square: [1, 1],
      '16/9': [16, 9],
      '4/3': [4, 3],
      '21/9': [21, 9],
    },
    fontFamily: {
      sans: ['"Noto Sans"', 'sans-serif'],
      serif: ['Georgia', 'Cambria'],
      mono: ['monospace'],
    },
  },
  variants: {
    extend: {
      display: ['hover', 'focus', 'group-hover', 'first', 'last'],
      fontWeight: ['hover', 'focus', 'active', 'group-hover'],
      textColor: ['hover', 'active', 'visited'],
      backgroundColor: ['odd', 'even'],
      fill: ['hover', 'focus'],
      borderColor: ['hover'],
      borderWidth: ['hover'],
      accessibility: ['hover', 'active', 'focus'],
      zIndex: ['hover', 'active', 'focus'],
      position: ['hover', 'focus', 'active'],
    },
  },
  plugins: [
    // require("@tailwindcss/forms")
  ],
  prefix: 'tw-',
  future: {
    removeDeprecatedGapUtilities: true,
  },
};
